inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable    # ← 新しい規約が登録された場合に、適用するかどうかの判定
  Exclude:
    - 'bin/**'
    - "lib/**/*"
    - "spec/**/*"
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'Gemfile'
    - 'brackets'
    - 'use_perl_names'

Style/Documentation:
  Enabled: false

Security/Open:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false
